# Generated by Django 4.1.7 on 2023-03-07 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Актеры',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Режиссеры',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('duration', models.TimeField(verbose_name='Длительность')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('аниме', 'аниме'), ('биографический', 'биографический'), ('боевик', 'боевик'), ('вестерн', 'вестерн'), ('военный', 'военный'), ('детектив', 'детектив'), ('детский', 'детский'), ('документальный', 'документальный'), ('драма', 'драма'), ('исторический', 'исторический'), ('кинокомикс', 'кинокомикс'), ('комедия', 'комедия'), ('концерт', 'концерт'), ('короткометражный', 'короткометражный'), ('криминал', 'криминал'), ('мелодрама', 'мелодрама'), ('мистика', 'мистика'), ('музыка', 'музыка'), ('мультфильм', 'мультфильм'), ('мюзикл', 'мюзикл'), ('научный', 'научный'), ('нуар', 'нуар'), ('приключения', 'приключения'), ('реалити-шоу', 'реалити-шоу'), ('семейный', 'семейный'), ('спорт', 'спорт'), ('ток-шоу', 'ток-шоу'), ('триллер', 'триллер'), ('ужасы', 'ужасы'), ('фантастика', 'фантастика'), ('фэнтези', 'фэнтези'), ('эротика', 'эротика')], default='Не указано', max_length=100, verbose_name='Жанр')),
                ('age_rating', models.IntegerField(choices=[(0, 0), (6, 6), (12, 12), (16, 16), (18, 18)], verbose_name='Возрастной рейтинг')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода фильма')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Бюджет')),
                ('fees_in_russia', models.IntegerField(blank=True, null=True, verbose_name='Сборы в России')),
                ('fees_in_the_world', models.IntegerField(blank=True, null=True, verbose_name='Сборы в мире')),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='Актеры')),
                ('directors', models.ManyToManyField(to='movies.director', verbose_name='Режиссеры')),
            ],
            options={
                'verbose_name': 'Фильмы',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='FilmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('founding_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Расположение')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Кинокомпания',
                'verbose_name_plural': 'Кинокомпания',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сериала')),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('аниме', 'аниме'), ('биографический', 'биографический'), ('боевик', 'боевик'), ('вестерн', 'вестерн'), ('военный', 'военный'), ('детектив', 'детектив'), ('детский', 'детский'), ('документальный', 'документальный'), ('драма', 'драма'), ('исторический', 'исторический'), ('кинокомикс', 'кинокомикс'), ('комедия', 'комедия'), ('концерт', 'концерт'), ('короткометражный', 'короткометражный'), ('криминал', 'криминал'), ('мелодрама', 'мелодрама'), ('мистика', 'мистика'), ('музыка', 'музыка'), ('мультфильм', 'мультфильм'), ('мюзикл', 'мюзикл'), ('научный', 'научный'), ('нуар', 'нуар'), ('приключения', 'приключения'), ('реалити-шоу', 'реалити-шоу'), ('семейный', 'семейный'), ('спорт', 'спорт'), ('ток-шоу', 'ток-шоу'), ('триллер', 'триллер'), ('ужасы', 'ужасы'), ('фантастика', 'фантастика'), ('фэнтези', 'фэнтези'), ('эротика', 'эротика')], default='Не указано', max_length=100, verbose_name='Жанр')),
                ('age_rating', models.IntegerField(choices=[(0, 0), (6, 6), (12, 12), (16, 16), (18, 18)], verbose_name='Возрастной рейтинг')),
                ('film_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmcompany', verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Сериалы',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SerialSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер сезона')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название сезона')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода сезона')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Бюджет')),
                ('fees_in_russia', models.IntegerField(blank=True, null=True, verbose_name='Сборы в России')),
                ('fees_in_the_world', models.IntegerField(blank=True, null=True, verbose_name='Сборы в мире')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.serial')),
            ],
            options={
                'verbose_name': 'Сезоны сериалов',
                'verbose_name_plural': 'Сезоны сериалов',
            },
        ),
        migrations.CreateModel(
            name='SerialEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер серии')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название серии')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода серии')),
                ('actors', models.ManyToManyField(to='movies.actor')),
                ('directors', models.ManyToManyField(to='movies.director')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.serial', verbose_name='Сериал')),
                ('serial_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.serialseason', verbose_name='Сезон сериала')),
            ],
            options={
                'verbose_name': 'Эпизоды сериалов',
                'verbose_name_plural': 'Эпизоды сериалов',
            },
        ),
        migrations.CreateModel(
            name='ReviewsSerialEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('review_text', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('serial_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.serialepisode', verbose_name='Серия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв об эпизоде сериала',
                'verbose_name_plural': 'Отзыв об эпизоде сериала',
            },
        ),
        migrations.CreateModel(
            name='ReviewsFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('review_text', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.film', verbose_name='Фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о фильме',
                'verbose_name_plural': 'Отзыв о фильме',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='film_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmcompany', verbose_name='Название компании'),
        ),
    ]
